import {
  TbSmartHome,
  TbReportAnalytics,
  TbWallet,
  TbUser,
  TbLogout,
  TbHeadphones,
  TbMailPlus,
  TbReceiptRefund,
  TbClipboardList,
  TbShieldLock,
} from "react-icons/tb";
import { FaFacebook, FaTwitter, FaInstagram } from "react-icons/fa";
import { BsStar } from "react-icons/bs";
import { AuthContext } from "../Navigation/AuthContext";
import { EMAIL_ID, PACKAGE_NAME } from "./Constant";

export const DummyAvatarForPassbook =
  "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/man-user-circle-icon.png";

export const BOTTOM_MENU_DATA = [
  {
    icon: TbSmartHome,
    name: "Home",
    route: "/",
    active: true,
  },
  {
    icon: TbReportAnalytics,
    name: "Reports",
    route: "/reports",
  },
  {
    icon: TbWallet,
    name: "Wallet",
    route: "/wallet",
  },
  {
    icon: TbUser,
    name: "Profile",
    route: "/profile",
  },
];
export const All_Recharge_Operator_List = [
  {
    Ezytm_Operator_code: 1,
    Egpayment_Operator_code: 1,
    Cyrus_Operator_code: "AT",
    A1_Operator_code: "A",
    PlanApi_Operator_code: 2,
    Billhub_Operator_code: "airtel",
    Mobikwik_Operator_code: 1,
    Operator_name: "Airtel",
    img: "https://ik.imagekit.io/43tomntsa/airtel.webp",
  },
  {
    Ezytm_Operator_code: 5,
    Egpayment_Operator_code: 6,
    Cyrus_Operator_code: "JIO",
    A1_Operator_code: "RC",
    PlanApi_Operator_code: 11,
    Billhub_Operator_code: "jio",
    Mobikwik_Operator_code: 140,
    Operator_name: "JIO",
    img: "https://ik.imagekit.io/43tomntsa/Jio.webp",
  },
  {
    Ezytm_Operator_code: 6,
    Egpayment_Operator_code: 5,
    Cyrus_Operator_code: "VF",
    A1_Operator_code: "V",
    PlanApi_Operator_code: 23,
    Billhub_Operator_code: "vi",
    Mobikwik_Operator_code: 338,
    Operator_name: "VI",
    img: "https://ik.imagekit.io/43tomntsa/VI.webp",
  },

  {
    Ezytm_Operator_code: 3,
    Egpayment_Operator_code: 2,
    Cyrus_Operator_code: "BSNL",
    A1_Operator_code: "BT",
    PlanApi_Operator_code: 4,
    Billhub_Operator_code: "bsnl_topup",
    Mobikwik_Operator_code: 3,
    Operator_name: "BSNL Topup",
    img: "https://ik.imagekit.io/43tomntsa/Bsnl.webp",
  },
  {
    Cyrus_Operator_code: "ATP",
    A1_Operator_code: "PAT",
    Billhub_Operator_code: "airtel_postpaid",
    Mobikwik_Operator_code: 29,

    Operator_name: "Airtel Postpaid",
    img: "https://ik.imagekit.io/43tomntsa/airtel.webp",
  },
  {
    Cyrus_Operator_code: "VFP",
    A1_Operator_code: "VP",
    Billhub_Operator_code: "vi_postpaid",
    Mobikwik_Operator_code: 436,

    Operator_name: "VI Postpaid",
    img: "https://ik.imagekit.io/43tomntsa/airtel.webp",
  },
  {
    Cyrus_Operator_code: "RJC",
    A1_Operator_code: "JPP",
    Billhub_Operator_code: "jio_postpaid",
    Mobikwik_Operator_code: 142,

    Operator_name: "JIO Postpaid",
    img: "https://ik.imagekit.io/43tomntsa/airtel.webp",
  },
];
export const All_Recharge_Circle_List = [
  {
    cyrus_circlecode: "36",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "ANDAMAN AND NICOBAR ISLANDS",
  },
  {
    cyrus_circlecode: "1",
    egpayment_circlecode: "1",
    ezytm_circlecode: "49",
    a1_circlecode: "13",
    planapi_circlecode: 49,
    Mobikwik_circlecode: 1,
    circlename: "Andhra Pradesh",
  },
  {
    cyrus_circlecode: "26",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "ARUNACHAL PRADESH",
  },
  {
    cyrus_circlecode: "2",
    egpayment_circlecode: "2",
    ezytm_circlecode: "56",
    a1_circlecode: "24",
    planapi_circlecode: "56",
    Mobikwik_circlecode: 2,
    circlename: "Assam",
  },
  {
    cyrus_circlecode: "3",
    egpayment_circlecode: "3",
    ezytm_circlecode: "52",
    a1_circlecode: "17",
    planapi_circlecode: "52",
    Mobikwik_circlecode: 3,
    circlename: "Bihar",
  },
  {
    cyrus_circlecode: "42",
    egpayment_circlecode: "3",
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 3,
    circlename: "Bihar and Jharkhand",
  },
  {
    cyrus_circlecode: "4",
    egpayment_circlecode: "4",
    ezytm_circlecode: "40",
    a1_circlecode: "7",
    planapi_circlecode: "40",
    Mobikwik_circlecode: 4,
    circlename: "Chennai",
  },
  {
    cyrus_circlecode: "27",
    egpayment_circlecode: null,
    ezytm_circlecode: "101",
    a1_circlecode: "27",
    planapi_circlecode: "101",
    Mobikwik_circlecode: 14,
    circlename: "CHHATTISGARH",
  },
  {
    cyrus_circlecode: "41",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "DADRA AND NAGAR",
  },
  {
    cyrus_circlecode: "40",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "DAMAN AND DIU",
  },
  {
    cyrus_circlecode: "5",
    egpayment_circlecode: "5",
    ezytm_circlecode: "10",
    a1_circlecode: "5",
    planapi_circlecode: "10",
    Mobikwik_circlecode: 5,
    circlename: "Delhi",
  },
  {
    cyrus_circlecode: "28",
    egpayment_circlecode: null,
    ezytm_circlecode: "102",
    a1_circlecode: null,
    planapi_circlecode: "102",
    Mobikwik_circlecode: 13,
    circlename: "GOA",
  },
  {
    cyrus_circlecode: "6",
    egpayment_circlecode: "6",
    ezytm_circlecode: "98",
    a1_circlecode: "12",
    planapi_circlecode: "98",
    Mobikwik_circlecode: 6,
    circlename: "Gujarat",
  },
  {
    cyrus_circlecode: "7",
    egpayment_circlecode: "7",
    ezytm_circlecode: "96",
    a1_circlecode: "20",
    planapi_circlecode: "96",
    Mobikwik_circlecode: 7,
    circlename: "Haryana",
  },
  {
    cyrus_circlecode: "8",
    egpayment_circlecode: "8",
    ezytm_circlecode: "03",
    a1_circlecode: "21",
    planapi_circlecode: "03",
    Mobikwik_circlecode: 8,
    circlename: "Himachal Pradesh",
  },
  {
    cyrus_circlecode: "9",
    egpayment_circlecode: "9",
    ezytm_circlecode: "55",
    a1_circlecode: "25",
    planapi_circlecode: "55",
    Mobikwik_circlecode: 9,
    circlename: "Jammu & Kashmir",
  },
  {
    cyrus_circlecode: "24",
    egpayment_circlecode: "3",
    ezytm_circlecode: "105",
    a1_circlecode: "22",
    planapi_circlecode: "105",
    Mobikwik_circlecode: 3,
    circlename: "Jharkhand",
  },
  {
    cyrus_circlecode: "10",
    egpayment_circlecode: "10",
    ezytm_circlecode: "06",
    a1_circlecode: "9",
    planapi_circlecode: "06",
    Mobikwik_circlecode: 10,
    circlename: "Karnataka",
  },
  {
    cyrus_circlecode: "11",
    egpayment_circlecode: "11",
    ezytm_circlecode: "95",
    a1_circlecode: "14",
    planapi_circlecode: "95",
    Mobikwik_circlecode: 11,
    circlename: "Kerala",
  },
  {
    cyrus_circlecode: "12",
    egpayment_circlecode: "12",
    ezytm_circlecode: "31",
    a1_circlecode: "6",
    planapi_circlecode: "31",
    Mobikwik_circlecode: 12,
    circlename: "Kolkata",
  },
  {
    cyrus_circlecode: "39",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "LAKSHADWEEP",
  },
  {
    cyrus_circlecode: "14",
    egpayment_circlecode: "14",
    ezytm_circlecode: "93",
    a1_circlecode: "16",
    planapi_circlecode: "93",
    Mobikwik_circlecode: 14,
    circlename: "Madhya Pradesh",
  },
  {
    cyrus_circlecode: "13",
    egpayment_circlecode: "13",
    ezytm_circlecode: "90",
    a1_circlecode: "4",
    planapi_circlecode: "90",
    Mobikwik_circlecode: 13,
    circlename: "Maharashtra",
  },
  {
    cyrus_circlecode: "29",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "MANIPUR",
  },
  {
    cyrus_circlecode: "30",
    egpayment_circlecode: null,
    ezytm_circlecode: "103",
    a1_circlecode: null,
    planapi_circlecode: "103",
    Mobikwik_circlecode: 51,
    circlename: "MEGHALAYA",
  },
  {
    cyrus_circlecode: "31",
    egpayment_circlecode: null,
    ezytm_circlecode: "104",
    a1_circlecode: null,
    planapi_circlecode: "104",
    Mobikwik_circlecode: 51,
    circlename: "MIZORAM",
  },
  {
    cyrus_circlecode: "15",
    egpayment_circlecode: "15",
    ezytm_circlecode: "92",
    a1_circlecode: "3",
    planapi_circlecode: "92",
    Mobikwik_circlecode: 15,
    circlename: "Mumbai",
  },
  {
    cyrus_circlecode: "32",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "NAGALAND",
  },
  {
    cyrus_circlecode: "16",
    egpayment_circlecode: "16",
    ezytm_circlecode: "16",
    a1_circlecode: "26",
    planapi_circlecode: "16",
    Mobikwik_circlecode: 16,
    circlename: "North East",
  },
  {
    cyrus_circlecode: "17",
    egpayment_circlecode: "17",
    ezytm_circlecode: "53",
    a1_circlecode: "23",
    planapi_circlecode: "53",
    Mobikwik_circlecode: 17,
    circlename: "Odisha",
  },
  {
    cyrus_circlecode: "38",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "PUDUCHERRY",
  },
  {
    cyrus_circlecode: "18",
    egpayment_circlecode: "18",
    ezytm_circlecode: "02",
    a1_circlecode: "1",
    planapi_circlecode: "02",
    Mobikwik_circlecode: 18,
    circlename: "Punjab",
  },
  {
    cyrus_circlecode: "19",
    egpayment_circlecode: "19",
    ezytm_circlecode: "70",
    a1_circlecode: "18",
    planapi_circlecode: "70",
    Mobikwik_circlecode: 19,
    circlename: "Rajasthan",
  },
  {
    cyrus_circlecode: "33",
    egpayment_circlecode: null,
    ezytm_circlecode: "99",
    a1_circlecode: null,
    planapi_circlecode: "99",
    Mobikwik_circlecode: 51,
    circlename: "SIKKIM",
  },
  {
    cyrus_circlecode: "20",
    egpayment_circlecode: "20",
    ezytm_circlecode: "94",
    a1_circlecode: "8",
    planapi_circlecode: "94",
    Mobikwik_circlecode: 20,
    circlename: "Tamil Nadu",
  },
  {
    cyrus_circlecode: "37",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 51,
    circlename: "TELANGANA",
  },
  {
    cyrus_circlecode: "25",
    egpayment_circlecode: null,
    ezytm_circlecode: "100",
    a1_circlecode: null,
    planapi_circlecode: "100",
    Mobikwik_circlecode: 51,
    circlename: "TRIPURA",
  },
  {
    cyrus_circlecode: "34",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 21,
    circlename: "UTTAR PRADESH",
  },
  {
    cyrus_circlecode: "21",
    egpayment_circlecode: "21",
    ezytm_circlecode: "54",
    a1_circlecode: "10",
    planapi_circlecode: "54",
    Mobikwik_circlecode: 21,
    circlename: "Uttar Pradesh - East",
  },
  {
    cyrus_circlecode: "22",
    egpayment_circlecode: "22",
    ezytm_circlecode: "97",
    a1_circlecode: "11",
    planapi_circlecode: "97",
    Mobikwik_circlecode: 22,
    circlename: "Uttar Pradesh - West",
  },
  {
    cyrus_circlecode: "35",
    egpayment_circlecode: null,
    ezytm_circlecode: null,
    a1_circlecode: null,
    planapi_circlecode: null,
    Mobikwik_circlecode: 22,
    circlename: "UTTARAKHAND",
  },
  {
    cyrus_circlecode: "23",
    egpayment_circlecode: "23",
    ezytm_circlecode: "51",
    a1_circlecode: "2",
    planapi_circlecode: "51",
    Mobikwik_circlecode: 23,
    circlename: "West Bengal",
  },
];

export const ProfileArr = [
  {
    title: "Privacy Policy",
    icon: TbShieldLock,
    route: "/privacy-policy",
  },
  {
    title: "Terms & Conditions",
    icon: TbClipboardList,
    route: "/terms-condcitions",
  },
  {
    title: "Refund Policy",
    icon: TbReceiptRefund,
    route: "/refund-policy",
  },
  {
    title: "BBPS Complaint",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT9Kk5ZklcaVdzaK9ORrixwIdDQ-ymuiDvxA&s",
    route: "/bbps-complaint-registration",
  },
  {
    title: "Write to us",
    icon: TbMailPlus,
    handleclick: () => window.open(`mailto:${EMAIL_ID}`, "_blank"),
  },
  {
    title: "Rate our App",
    icon: BsStar,
    route: "/profile",
    handleclick: () =>
      window.open(
        `https://play.google.com/store/apps/details?id=${PACKAGE_NAME}`,
        "_blank"
      ),
  },
  // {
  //   title: "Contact Support",
  //   icon: TbHeadphones,
  //   route: "/contact",
  // },
];
export const SocialArr = [
  {
    name: "Facebook",
    icon: <FaFacebook />,
    link: "https://www.facebook.com/",
  },
  {
    name: "Twitter",
    icon: <FaTwitter />,
    link: "https://www.twitter.com/",
  },
  {
    name: "Instagram",
    icon: <FaInstagram />,
    link: "https://www.instagram.com/",
  },
];
export const DTH_OPERATOR_ARR = [
  {
    id: "airtel_tv",
    img: "https://ik.imagekit.io/43tomntsa/airtel.png",
    title: "Airtel Digital TV",
    placeholder: "Customer ID",
    findContent: `Press the Menu button on your remote and select 'My Account' to get your Subscriber ID or SMS 'BAL' to 54325 or give a missed call to 81300-81300 from your registered mobile number.`,
  },
  {
    id: "dish_tv",
    img: "https://ik.imagekit.io/43tomntsa/dish_tv.webp",
    title: "Dish TV",
    placeholder: "Card Number",
    findContent: `Go to the help menu on your TV and select My Account to find your Viewing Card Number.`,
  },
  {
    id: "sun_tv",
    img: "https://ik.imagekit.io/43tomntsa/SunDirect.webp",
    title: "Sun Direct",
    placeholder: "Customer ID",
    findContent: `SMS 'ID' to 9212012299 from your registered mobile number or SMS 'CID' <Smart Card Number> from non-registered mobile number to 9212012299.`,
  },
  {
    id: "tata_sky",
    img: "https://ik.imagekit.io/43tomntsa/TataPlay.webp",
    title: "Tata Play",
    placeholder: "Subscriber No.",
    findContent: `Press HOME button on your remote or give a missed call to 080-61-9999-11 from your registered mobile number.`,
  },
  {
    id: "videocon",
    img: "https://ik.imagekit.io/43tomntsa/VideoCon.webp",
    title: "Videocon D2H",
    placeholder: "Customer ID",
    findContent: `SMS 'ID' to 566777 or call 97818-97818 (Toll Free) from your registered mobile number.`,
  },
];
